B2B_PLATFORM_SEEDS = [
    {
        "platform_key": "thomasnet",
        "name": "ThomasNet",
        "domain": "thomasnet.com",
        "source_type": "directory",
        "regions": "US, North America",
        "industry_tags": "industrial, manufacturing, supplier discovery",
        "base_url": "https://www.thomasnet.com/",
        "listing_model": "directory_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "北美工业采购目录。适合供应商档案认领、品类补全、官网和认证信息一致性维护；不做自动登录提交。",
    },
    {
        "platform_key": "iqs_directory",
        "name": "IQS Directory",
        "domain": "iqsdirectory.com",
        "source_type": "directory",
        "regions": "US, North America",
        "industry_tags": "industrial, OEM, manufacturers, suppliers",
        "base_url": "https://www.iqsdirectory.com/",
        "listing_model": "directory_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "北美制造商、供应商和分销商目录。适合补公司档案、品类、认证、官网链接；提交和付费套餐必须人工确认。",
    },
    {
        "platform_key": "globalspec",
        "name": "GlobalSpec / Engineering360",
        "domain": "globalspec.com",
        "source_type": "directory",
        "regions": "US, Global",
        "industry_tags": "engineering, components, specifications",
        "base_url": "https://www.globalspec.com/",
        "listing_model": "directory_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "工程和技术产品检索源。优先核对供应商、规格、品类和官网链接。",
    },
    {
        "platform_key": "engineering360",
        "name": "Engineering360 Supplier Directory",
        "domain": "engineering360.com",
        "source_type": "directory",
        "regions": "US, Global",
        "industry_tags": "engineering, supplier directory, product specification",
        "base_url": "https://www.engineering360.com/",
        "listing_model": "directory_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "GlobalSpec/Engineering360 生态内的工程供应商资料源。适合规格型产品和官网可引用资产对齐。",
    },
    {
        "platform_key": "industrynet",
        "name": "IndustryNet",
        "domain": "industrynet.com",
        "source_type": "directory",
        "regions": "US, North America",
        "industry_tags": "industrial suppliers, RFQ",
        "base_url": "https://www.industrynet.com/",
        "listing_model": "directory_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "北美工业供应商发现源。适合 profile_create/profile_update，提交结果必须回填 result_url。",
    },
    {
        "platform_key": "macraes_blue_book",
        "name": "MacRAE'S Blue Book",
        "domain": "macraesbluebook.com",
        "source_type": "directory",
        "regions": "US, Canada",
        "industry_tags": "industrial directory, manufacturing, suppliers",
        "base_url": "https://www.macraesbluebook.com/",
        "listing_model": "directory_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "北美工业目录。适合查询是否已有品牌档案、补充公司信息和目标产品类别。",
    },
    {
        "platform_key": "kompass",
        "name": "Kompass",
        "domain": "kompass.com",
        "source_type": "directory",
        "regions": "Global, EU",
        "industry_tags": "global b2b, company directory",
        "base_url": "https://www.kompass.com/",
        "listing_model": "directory_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "全球 B2B 公司目录。适合出口企业多语种档案和品类描述核对。",
    },
    {
        "platform_key": "europages",
        "name": "Europages",
        "domain": "europages.com",
        "source_type": "marketplace",
        "regions": "EU, Global",
        "industry_tags": "europe b2b, exporter",
        "base_url": "https://www.europages.com/",
        "listing_model": "marketplace",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "欧洲 B2B 平台。适合 profile_update、product_listing，多语种内容必须人工终审。",
    },
    {
        "platform_key": "wlw",
        "name": "Wer liefert was (WLW)",
        "domain": "wlw.de",
        "source_type": "directory",
        "regions": "DE, DACH, EU",
        "industry_tags": "germany b2b, supplier directory, industrial",
        "base_url": "https://www.wlw.de/",
        "listing_model": "directory_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "德语区 B2B 供应商目录。适合面向德国/欧盟市场的供应商档案和德语品类描述维护。",
    },
    {
        "platform_key": "exportpages",
        "name": "Exportpages",
        "domain": "exportpages.com",
        "source_type": "directory",
        "regions": "EU, Global",
        "industry_tags": "export directory, b2b, suppliers",
        "base_url": "https://www.exportpages.com/",
        "listing_model": "directory_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "出口供应商目录。适合补英文资料和目标品类，但需人工判断页面质量与询盘价值。",
    },
    {
        "platform_key": "directindustry",
        "name": "DirectIndustry",
        "domain": "directindustry.com",
        "source_type": "directory",
        "regions": "EU, Global",
        "industry_tags": "industrial products, equipment, product directory",
        "base_url": "https://www.directindustry.com/",
        "listing_model": "product_directory",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "工业产品目录，常出现在搜索和 AI 来源发现中。适合产品、型号、规格和官网链接核对。",
    },
    {
        "platform_key": "mfg",
        "name": "MFG.com",
        "domain": "mfg.com",
        "source_type": "marketplace",
        "regions": "US, Global",
        "industry_tags": "custom manufacturing, RFQ, machining",
        "base_url": "https://www.mfg.com/",
        "listing_model": "marketplace",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "定制制造和 RFQ 平台。更偏获客与能力露出，不把提交视为 SEO 提升保证。",
    },
    {
        "platform_key": "xometry",
        "name": "Xometry Supplier Network",
        "domain": "xometry.com",
        "source_type": "marketplace",
        "regions": "US, EU",
        "industry_tags": "custom manufacturing, CNC, sheet metal, injection molding",
        "base_url": "https://www.xometry.com/",
        "listing_model": "merchant_console",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "定制制造网络，适合能力型制造企业评估入驻。供应侧动作走客户自有账号和平台规则。",
    },
    {
        "platform_key": "alibaba",
        "name": "Alibaba.com",
        "domain": "alibaba.com",
        "source_type": "marketplace",
        "regions": "Global",
        "industry_tags": "export marketplace, wholesale, supplier storefront",
        "base_url": "https://www.alibaba.com/",
        "listing_model": "merchant_console",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "出口 B2B marketplace。只管理客户自有商家后台任务、内容资产和 result_url 核验，不做自动铺货或群发询盘。",
    },
    {
        "platform_key": "made_in_china",
        "name": "Made-in-China",
        "domain": "made-in-china.com",
        "source_type": "marketplace",
        "regions": "Global",
        "industry_tags": "china exporter, marketplace, product listing",
        "base_url": "https://www.made-in-china.com/",
        "listing_model": "merchant_console",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "中国出口供应商平台。适合商家资料、产品 listing 和官网一致性核验；不替代客户后台人工确认。",
    },
    {
        "platform_key": "global_sources",
        "name": "Global Sources",
        "domain": "globalsources.com",
        "source_type": "marketplace",
        "regions": "Asia, Global",
        "industry_tags": "export marketplace, trade show, supplier profile",
        "base_url": "https://www.globalsources.com/",
        "listing_model": "merchant_console",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "亚洲出口供应商平台。适合商家档案、展会/供应商资料和产品信息一致性管理。",
    },
    {
        "platform_key": "indiamart",
        "name": "IndiaMART",
        "domain": "indiamart.com",
        "source_type": "marketplace",
        "regions": "India, Global",
        "industry_tags": "b2b marketplace, supplier profile",
        "base_url": "https://www.indiamart.com/",
        "listing_model": "merchant_console",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "印度 B2B marketplace。适合竞品和市场参考，也可用于客户已有账号任务管理。",
    },
    {
        "platform_key": "tradekey",
        "name": "TradeKey",
        "domain": "tradekey.com",
        "source_type": "marketplace",
        "regions": "Global, Middle East, Asia",
        "industry_tags": "b2b marketplace, exporter",
        "base_url": "https://www.tradekey.com/",
        "listing_model": "marketplace",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "全球 B2B marketplace。适合候选机会和竞品露出监控，执行前需人工判断平台质量。",
    },
    {
        "platform_key": "ec21",
        "name": "EC21",
        "domain": "ec21.com",
        "source_type": "marketplace",
        "regions": "Asia, Global",
        "industry_tags": "b2b marketplace, exporter",
        "base_url": "https://www.ec21.com/",
        "listing_model": "marketplace",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "亚洲/全球 B2B marketplace。适合作为候选曝光源，不做自动注册和批量发布。",
    },
    {
        "platform_key": "nam",
        "name": "National Association of Manufacturers (NAM)",
        "domain": "nam.org",
        "source_type": "association",
        "regions": "US",
        "industry_tags": "manufacturing association, member directory",
        "base_url": "https://nam.org/",
        "listing_model": "association_member",
        "submission_mode": "email_outreach",
        "risk_level": "low",
        "notes": "美国制造业协会。适合会员/认证/公司信息一致性核验；不能冒充会员或自动提交虚假资料。",
    },
    {
        "platform_key": "nema",
        "name": "NEMA Member Directory",
        "domain": "makeitelectric.org",
        "source_type": "association",
        "regions": "US",
        "industry_tags": "electrical, manufacturing, association",
        "base_url": "https://www.makeitelectric.org/membership/membership-directory/",
        "listing_model": "association_member",
        "submission_mode": "email_outreach",
        "risk_level": "low",
        "notes": "电气制造业协会会员目录。适合电气/电子/能源客户做会员信息和官网链接核验。",
    },
    {
        "platform_key": "ieee_sa_entity_members",
        "name": "IEEE SA Entity Members",
        "domain": "standards.ieee.org",
        "source_type": "association",
        "regions": "Global",
        "industry_tags": "standards, electronics, technology, entity member",
        "base_url": "https://standards.ieee.org/about/membership/organizations/full-member-listing/",
        "listing_model": "association_member",
        "submission_mode": "api_none",
        "risk_level": "low",
        "notes": "标准协会实体会员列表。适合做标准/会员事实核验，默认只监控，不自动写入。",
    },
    {
        "platform_key": "csia_exchange",
        "name": "CSIA Exchange",
        "domain": "controlsys.org",
        "source_type": "association",
        "regions": "US, Global",
        "industry_tags": "automation, system integrator, controls",
        "base_url": "https://controlsys.org/find-an-integrator/",
        "listing_model": "association_member",
        "submission_mode": "manual_login",
        "risk_level": "low",
        "notes": "控制系统集成商协会目录。适合自动化、控制系统、系统集成类客户或竞品来源发现。",
    },
    {
        "platform_key": "mana_directory",
        "name": "MANA Representative Directory",
        "domain": "manaonline.org",
        "source_type": "association",
        "regions": "US",
        "industry_tags": "manufacturer representatives, channel, distributor",
        "base_url": "https://www.manaonline.org/",
        "listing_model": "association_member",
        "submission_mode": "email_outreach",
        "risk_level": "low",
        "notes": "制造商代理协会资源。适合渠道/代理商机会发现和商务联系，不做自动外联群发。",
    },
    {
        "platform_key": "engineering_media",
        "name": "Engineering / Industrial Media",
        "domain": "engineering.com",
        "source_type": "media",
        "regions": "US, Global",
        "industry_tags": "media, listicle, PR, roundup",
        "base_url": "https://www.engineering.com/",
        "listing_model": "media",
        "submission_mode": "email_outreach",
        "risk_level": "high",
        "notes": "行业媒体、榜单、测评和 PR 入口的代表资源。只生成 pitch/媒体包草稿，必须人工发送和终审。",
    },
    {
        "platform_key": "machine_design",
        "name": "Machine Design",
        "domain": "machinedesign.com",
        "source_type": "media",
        "regions": "US, Global",
        "industry_tags": "industrial media, engineering, listicle, buyer guide",
        "base_url": "https://www.machinedesign.com/",
        "listing_model": "media",
        "submission_mode": "email_outreach",
        "risk_level": "high",
        "notes": "工程媒体。适合榜单、案例、专家稿和媒体 pitch 草稿；不得无人审投稿或自动购买付费位。",
    },
    {
        "platform_key": "control_engineering",
        "name": "Control Engineering",
        "domain": "controleng.com",
        "source_type": "media",
        "regions": "US, Global",
        "industry_tags": "automation, controls, industrial media",
        "base_url": "https://www.controleng.com/",
        "listing_model": "media",
        "submission_mode": "email_outreach",
        "risk_level": "high",
        "notes": "自动化和控制工程媒体。适合技术案例、行业观点、榜单机会，人审后外联。",
    },
    {
        "platform_key": "industrial_machinery_digest",
        "name": "Industrial Machinery Digest",
        "domain": "industrialmachinerydigest.com",
        "source_type": "media",
        "regions": "US, Global",
        "industry_tags": "industrial machinery, supplier directory, media",
        "base_url": "https://www.industrialmachinerydigest.com/",
        "listing_model": "media_directory",
        "submission_mode": "email_outreach",
        "risk_level": "high",
        "notes": "工业机械媒体和供应商目录入口。适合媒体包、目录资料和榜单机会管理，所有公开内容需人工终审。",
    },
    {
        "platform_key": "distributor_pages",
        "name": "Distributor / Partner Pages",
        "domain": "",
        "source_type": "distributor",
        "regions": "Target markets",
        "industry_tags": "dealer, distributor, partner, reseller",
        "base_url": "",
        "listing_model": "distributor",
        "submission_mode": "email_outreach",
        "risk_level": "low",
        "notes": "客户真实分销商、代理商、合作伙伴页面。重点是品牌名、官网链接、型号和描述一致性。",
    },
    {
        "platform_key": "partner_directories",
        "name": "Partner / Dealer Directories",
        "domain": "",
        "source_type": "distributor",
        "regions": "Target markets",
        "industry_tags": "partner directory, dealer locator, reseller",
        "base_url": "",
        "listing_model": "partner_directory",
        "submission_mode": "email_outreach",
        "risk_level": "low",
        "notes": "客户授权渠道、dealer locator、partner directory。通过商务/客户关系修正页面，系统负责材料、任务和核验。",
    },
    {
        "platform_key": "reddit_industry",
        "name": "Reddit Industry Communities",
        "domain": "reddit.com",
        "source_type": "community",
        "regions": "Global",
        "industry_tags": "community, q&a, monitoring",
        "base_url": "https://www.reddit.com/",
        "listing_model": "community_monitor",
        "submission_mode": "api_none",
        "risk_level": "high",
        "notes": "只做监测、问题发现和人工回答草稿。禁止自动发帖、自动评论、批量插链接。",
    },
    {
        "platform_key": "stack_exchange",
        "name": "Stack Exchange / Stack Overflow",
        "domain": "stackexchange.com",
        "source_type": "community",
        "regions": "Global",
        "industry_tags": "q&a, developer, technical community",
        "base_url": "https://stackexchange.com/",
        "listing_model": "community_monitor",
        "submission_mode": "api_none",
        "risk_level": "high",
        "notes": "适合软件、开发者工具和工程技术问答监测。回答必须人工参与，不能自动发帖。",
    },
    {
        "platform_key": "quora",
        "name": "Quora",
        "domain": "quora.com",
        "source_type": "community",
        "regions": "Global",
        "industry_tags": "q&a, awareness, monitoring",
        "base_url": "https://www.quora.com/",
        "listing_model": "community_monitor",
        "submission_mode": "api_none",
        "risk_level": "high",
        "notes": "可监测问题和生成回答草稿，是否参与由人工判断。禁止自动回答或批量带链接。",
    },
    {
        "platform_key": "linkedin_company",
        "name": "LinkedIn Company Page",
        "domain": "linkedin.com",
        "source_type": "social_profile",
        "regions": "Global",
        "industry_tags": "company entity, social proof, executive profile",
        "base_url": "https://www.linkedin.com/",
        "listing_model": "company_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "公司实体和品牌可信度基础源。可管理资料一致性和人工发布计划，禁止自动加好友/群发。",
    },
    {
        "platform_key": "x_twitter",
        "name": "X / Twitter Official Account",
        "domain": "x.com",
        "source_type": "social_profile",
        "regions": "Global",
        "industry_tags": "brand profile, social proof, announcements, monitoring",
        "base_url": "https://x.com/",
        "listing_model": "social_profile",
        "submission_mode": "manual_login",
        "risk_level": "high",
        "notes": "客户官方账号维护入口。适合统一品牌名、官网链接、简介和公告；禁止自动刷帖、自动私信、自动评论和批量插链接。",
    },
    {
        "platform_key": "facebook_page",
        "name": "Facebook Page",
        "domain": "facebook.com",
        "source_type": "social_profile",
        "regions": "Global",
        "industry_tags": "brand page, social proof, company updates",
        "base_url": "https://www.facebook.com/",
        "listing_model": "social_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "客户官方主页维护入口。重点核对品牌名、官网、联系信息和地区；所有帖子和广告动作必须人工确认。",
    },
    {
        "platform_key": "youtube_channel",
        "name": "YouTube Channel",
        "domain": "youtube.com",
        "source_type": "social_profile",
        "regions": "Global",
        "industry_tags": "video, product demo, factory tour, brand proof",
        "base_url": "https://www.youtube.com/",
        "listing_model": "social_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "适合 B2B 产品演示、工厂视频、安装说明和案例素材。系统只管理资料、任务和上线 URL，不自动上传公开视频。",
    },
    {
        "platform_key": "instagram_business",
        "name": "Instagram Business Profile",
        "domain": "instagram.com",
        "source_type": "social_profile",
        "regions": "Global",
        "industry_tags": "visual brand, product photos, social proof",
        "base_url": "https://www.instagram.com/",
        "listing_model": "social_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "适合展示产品图片、展会、工厂和品牌视觉。适合作为基础阵地维护，不做自动关注、私信和批量互动。",
    },
    {
        "platform_key": "tiktok_business",
        "name": "TikTok Business Account",
        "domain": "tiktok.com",
        "source_type": "social_profile",
        "regions": "Global",
        "industry_tags": "short video, brand awareness, product demo",
        "base_url": "https://www.tiktok.com/business/",
        "listing_model": "social_profile",
        "submission_mode": "manual_login",
        "risk_level": "high",
        "notes": "适合短视频内容测试和品牌露出。客户人工确认内容后发布；不做自动刷量、自动评论或违规私信。",
    },
    {
        "platform_key": "pinterest_business",
        "name": "Pinterest Business",
        "domain": "pinterest.com",
        "source_type": "social_profile",
        "regions": "US, EU, Global",
        "industry_tags": "visual discovery, catalog, product inspiration",
        "base_url": "https://business.pinterest.com/",
        "listing_model": "social_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "适合视觉型产品、家居、包装、材料、消费类 B2B 场景。用于账号资料和内容计划管理，发布需人工确认。",
    },
    {
        "platform_key": "opencorporates",
        "name": "OpenCorporates",
        "domain": "opencorporates.com",
        "source_type": "knowledge_graph",
        "regions": "Global",
        "industry_tags": "company data, entity disambiguation",
        "base_url": "https://opencorporates.com/",
        "listing_model": "company_data",
        "submission_mode": "api_none",
        "risk_level": "low",
        "notes": "公司数据和实体消歧参考。默认用于监控名称、地址、官网一致性，不做伪造公司信息。",
    },
    {
        "platform_key": "wikidata",
        "name": "Wikidata",
        "domain": "wikidata.org",
        "source_type": "knowledge_graph",
        "regions": "Global",
        "industry_tags": "entity, knowledge graph, citation",
        "base_url": "https://www.wikidata.org/",
        "listing_model": "knowledge_graph",
        "submission_mode": "api_none",
        "risk_level": "high",
        "notes": "知识图谱实体源。只适合有充分第三方来源的品牌，不自动创建或编造实体资料。",
    },
    {
        "platform_key": "google_business_profile",
        "name": "Google Business Profile",
        "domain": "google.com",
        "source_type": "knowledge_graph",
        "regions": "Target markets",
        "industry_tags": "local entity, map, company profile",
        "base_url": "https://www.google.com/business/",
        "listing_model": "company_profile",
        "submission_mode": "manual_login",
        "risk_level": "medium",
        "notes": "有实体地址的客户可维护公司名、官网、地址和营业信息一致性。账号和验证码必须人工处理。",
    },
    {
        "platform_key": "link_checker",
        "name": "Link Checker / Lychee / Linkinator",
        "domain": "",
        "source_type": "monitoring",
        "regions": "Global",
        "industry_tags": "link validation, placement check, monitoring",
        "base_url": "",
        "listing_model": "system_job",
        "submission_mode": "api_none",
        "risk_level": "low",
        "notes": "站外 placement 核验工具类型。用于检查 result_url、HTTP、目标链接、rel、页面变化，不代表排名或 GEO 已提升。",
    },
    {
        "platform_key": "changedetection",
        "name": "changedetection.io / ArchiveBox",
        "domain": "",
        "source_type": "monitoring",
        "regions": "Global",
        "industry_tags": "page change, archive, evidence",
        "base_url": "",
        "listing_model": "system_job",
        "submission_mode": "api_none",
        "risk_level": "low",
        "notes": "第三方页面变化监控和证据归档工具类型。用于保留上线证据和删除/改链提醒。",
    },
]
